ARG VERSION=latest

FROM --platform=$BUILDPLATFORM pjpimentel/geolite:${VERSION} AS data

RUN ["/geolite", "--data-path", "/data", "build", "__COUNTRY__"]

FROM pjpimentel/geolite:${VERSION}
COPY --from=data --chown=10001:10001 /data /.geolite
CMD ["--data-path", "/.geolite", "http-server"]
