ARG VERSION=latest

FROM --platform=$BUILDPLATFORM pjpimentel/geolite:${VERSION} AS data

RUN ["/geolite", "build", "__COUNTRY__"]

FROM pjpimentel/geolite:${VERSION}
COPY --from=data --chown=10001:10001 /.geolite /.geolite
CMD ["http-server"]
