name: pre-build-quality-check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  pre_build_quality_check:
    name: pre-build-quality-check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: typos check
        uses: crate-ci/typos@3bc303c295c081add5df4a4d52a1e117f2fb2dce

      - name: setup rust toolchain
        uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30
        with:
          components: rustfmt, clippy, llvm-tools-preview

      - name: install cargo-audit
        uses: taiki-e/install-action@5626e41434f03ab3022d9685405c0645c879f441

      - name: install cargo-llvm-cov
        uses: taiki-e/install-action@5626e41434f03ab3022d9685405c0645c879f441
        with:
          tool: cargo-llvm-cov

      - name: cargo fmt check
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: cargo audit
        run: cargo audit

      - name: cargo test with coverage
        run: cargo llvm-cov --all-targets --lcov --output-path lcov.info

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -Dsonar.qualitygate.wait=true
